version: '3.3'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - spring-mysql

  spring-boot:
      image: nodirshox/sa-csv-batch:latest
      restart: always
      container_name: spring-batch
      ports:
        - 3000:3000
      depends_on:
        - db
      networks:
        - spring-mysql
volumes:
  my-db:
networks:
  spring-mysql:
