version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - spring-mysql

  spring-boot:
      image: spring-batch:latest
      restart: always
      container_name: spring-batch
      ports:
        - 8080:8080
      depends_on:
        - db
      networks:
        - spring-mysql
volumes:
  my-db:
networks:
  spring-mysql: